

```{r}
library(dplyr)
#install.packages('Lahman')
library(Lahman)

batting <- Lahman::Batting %>%
  as_tibble() %>%
  select(playerID, yearID, teamID, G, AB:H) %>%
  arrange(playerID, yearID, teamID) %>%
  semi_join(Lahman::AwardsPlayers, by = "playerID")

players <- batting %>% group_by(playerID)
players

```
```{r}
# For each player, find the two years with most hits
filter(players, min_rank(desc(H)) <= 2 & H > 0)
```

```{r}
# Within each player, rank each year by the number of games played
mutate(players, G_rank = min_rank(G))
```

```{r}
# For each player, find every year that was better than the previous year
filter(players, G > lag(G))
```

```{r}
# For each player, compute avg change in games played per year
mutate(players, G_change = (G - lag(G)) / (yearID - lag(yearID)))
```

```{r}
# For each player, find all where they played more games than average
filter(players, G > mean(G))
```

```{r}
# For each, player compute a z score based on number of games played
mutate(players, G_z = (G - mean(G)) / sd(G)) -> players_g_z
players_g_z
```

```{r}
library(dplyr)
library(ggplot2)
# geom_bar is designed to make it easy to create bar charts that show
# counts (or sums of weights)
g <- ggplot(mpg, aes(class))
mpg
# Number of cars in each class:
g + geom_bar()
# Total engine displacement of each class
g + geom_bar(aes(weight = displ))


g<-ggplot(mpg)
g + geom_bar(aes(manufacturer))

# Bar charts are automatically stacked when multiple bars are placed
# at the same location. The order of the fill is designed to match
# the legend
g + geom_bar(aes(manufacturer,fill = class))

# If you need to flip the order (because you've flipped the plot)
# call position_stack() explicitly:
g +
 geom_bar(aes(class, fill = drv), position = position_stack(reverse = TRUE)) +
 #coord_flip() #+
 theme(legend.position = "top")

# To show (e.g.) means, you need geom_col()
df <- data.frame(trt = c("a", "b", "c"), outcome = c(2.3, 1.9, 3.2))
ggplot(df, aes(trt, outcome)) +
  geom_col()
# But geom_point() displays exactly the same information and doesn't
# require the y-axis to touch zero.
ggplot(df, aes(trt, outcome)) +
  geom_point()

# You can also use geom_bar() with continuous data, in which case
# it will show counts at unique locations
df <- data.frame(x = rep(c(2.9, 3.1, 4.5), c(5, 10, 4)))
ggplot(df, aes(x)) + geom_bar()
# cf. a histogram of the same data
ggplot(df, aes(x)) + geom_histogram(binwidth = 0.5)
```

